### ISSUE TITLE
Usage with preprocessors?

### ISSUE THREAD

**Issue by frostney** [Nitive/babel-plugin-css-modules-react#1]
It is possible to use this plugin with CSS preprocessors? (LESS, SASS, etc.)
If yes, would you mind adding a short example for that use case.

**Comment by Nitive** [comment]
Yes, you can do that. Just import .less/.sass file instead of .css

``` js
import styles from './styles.sass'
```

Your build system should be configured for not javascript modules, for example, you should use `sass-loader` if you use webpack.
